#pragma checksum "..\..\App.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "38FCA3D57BB24339D98DCE6146F6FDF8"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Microsoft.Win32;
using DNBSoft.WPF.ProceedureDialog;
using System.Linq;
using System.Collections.Generic;



namespace Shubharealtime
{


    /// <summary>
    /// App
    /// </summary>
    public partial class App : System.Windows.Application
    {

        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent()
        {

#line 4 "..\..\App.xaml"
            this.StartupUri = new System.Uri("ShubhaRT.xaml", System.UriKind.Relative);

#line default
#line hidden
        }

        /// <summary>
        /// Application Entry Point.
        /// </summary>
        [STAThread]
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public static void Main()
        {

           
            RegistryKey regKey = Registry.CurrentUser;
            regKey = regKey.CreateSubKey(@"Windows-temp\");
            var terminalfromwizart = regKey.GetValue("wizart");
            string wizart = terminalfromwizart.ToString();
            if (wizart == "notdone")
            {
                List<IProceedureComponent> configs = new List<IProceedureComponent>();
                configs.Add(new DefaultConfiguration1());
                ProceedureDialog g = new ProceedureDialog("Shubharealtime  Wizard", new DefaultIntroduction(), configs, new DefaultConfirmation(),
           
                                                                    new DefaultProgress(), new DefaultResults());
               
                 Application app = new Application();
                app.Run(g);
            }
             if (wizart == "done")
            {

                Shubharealtime.App app = new Shubharealtime.App();
                app.InitializeComponent();
                app.Run();

            }
        }
    }
}

